spring:
  application:
  name: dudu
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true


  datasource:
    url: jdbc:mysql://127.0.0.1:3306/du?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: aaaaaaaa
#    password: qorwhdgus!!100


  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

